package:
  name: jrgui
  version: 0.1.0

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=3.5
    - setuptools
    - rdkit >=2017.03.3
    - pandas >=0.20
  run:
    - python >=3.5
    - setuptools
    - rdkit >=2017.03.3
    - pandas >=0.20

about:
  home: https://github.com/curieshicy/JRgui
  summary: a GUI for JR method
  license: MIT
